### ISSUE TITLE
Will there be a web support?

### ISSUE THREAD

**Issue by engblnk** [ra1u/redis-dart#18]
Thanks for the good work.

**Comment by ra1u** [comment]
Hi @engblnk 

Can you please, better explain what you have in mind by web support?

**Comment by engblnk** [comment]
Right :),
I intend to build a dynamic webpage, basicly updating lists of data streaming from redis.
I want use flutter web since I have already some experience in flutter.

In https://pub.dev/packages/redis it states that, this package supports iOS and Android but Web is not there.

Best Regards,
Engin

**Comment by ra1u** [comment]
I will take a look into what can be done. 

Current implementation is using raw socket to connect on redis, where web browsers can communicate only trough http. 

@engblnk  how do you plan to connect on redis?

**Comment by engblnk** [comment]
I get it now. I am not sure.

The lists will be highly volatile, up to 5000 updates in every second. 
@ra1u Should I consider any performance issues if I use http?

**Comment by ra1u** [comment]
Handling lot of  http request concurrently in web-browser, particularly in java script might be a tricky.  However if your concern is performance and you are unable to aggregate requests you can try using websockets. 

For this you would need to get websocket translator to redis (i am not sure that redis provides websocket connection), and modify redis-dart library for support of web-sockets instead of just sockets.

**Comment by engblnk** [comment]
I understand now, thank you very much.
Now, things got complicated then it suppose to be. :)

**Comment by abhin-vicks** [comment]
Please let us know if any update comes for web support.

**Comment by TheOneWithTheBraid** [comment]
I think it will be nether possible nor useful to have redis in web. In such a use case, a server side implementation featuring websocket communication might be more useful.
